numberone=int(input("Please enter your Sub-Total"))
numbertwo=int(input("Please enter the percentage of tax/dividends without the % sign"))
answer=(numberone/100)
answer=(answer*numbertwo)
print(answer)
